config/routes.rb
Rails.application.routes.draw do
  get 'galleries/index'

  #get 'shop/index'

  devise_for :users
  resources :budgets
  resources :products 
  resources :categories
  resources :galleries
  resources :shop do
  	member do
  		post "add"
      post "restar"
      post "suma"
      post "deletedetalle"
      get "pdf"
      
  	end
      collection do
        get  "showallbudget"
      end 

  end
  root 'shop#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_cabecera.html.erb
<div class="header_bg">
<div class="wrap">
	<div class="header">
			<div class="row">
				<div class="col-md-2">
			

				</div>
				<div class="col-md-2 col-md-offset-8">
				<% if cookies[:budget_id] %>
					<%= link_to shop_path( cookies[:budget_id] ),class: "quick-btn" do %>
						<i class="fa fa-shopping-cart fa-2x"></i> 
						<span>$ <%= cookies[:moneda_total]%></span>
						<% if cookies[:total_cart]%>
						<span class="label label-default"><%= cookies[:total_cart] %></span>


						<% end %>
					<%end%>

				<%else%>
					<a class="quick-btn" href="#">
					<i class="fa fa-shopping-cart fa-2x"></i>
					<span>$ 0</span>
						
							<span class="label label-default">0</span>
							
							
					
					
					</a>

				<%end%>
			
	

				</div>
			</div>



	


	
		</div>
		<div class="clear"></div>




	</div>
</div>
</div>

app/views/partials/_navigations.html.erb
<div class="menus">
<nav class="navbar navbar-default">
 

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Home', root_path(), class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

<% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Productos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Ver Productos', products_path %></li>
            <li><%= link_to 'Nuevo Producto', new_product_url %></li>

          </ul>
        </li>
<%end%>
<% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Ver Categorias', categories_path %></li>
            <li><%= link_to 'Nueva Categoria', new_category_url %></li>
         
          </ul>
        </li>
        <%end%>
        <% if user_signed_in? %>
   <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Presupuestos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li><%= link_to "Ver todos los Presupuestos",budgets_path %></li>

          </ul>
        </li>
<%end%>



      </ul>
  


      <ul class="nav navbar-nav navbar-right">



      
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sesion <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% if user_signed_in? %>
                <li>
                <%= link_to('Salir', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Iniciar', new_user_session_path)  %>  
                </li>
                  <li role="separator" class="divider"></li>
                  <li>
                <%= link_to('Registrarse', new_user_registration_path)  %>
                </li>
              <% end %>

          
           
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



</div>

app/views/partials/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">

      <%= image_tag ("slider1.png")%>
    </div>

    <div class="item">
      <%= image_tag ("slider2.png")%>
    </div>

    <div class="item">
      <%= image_tag ("slider3.png")%>
    </div>

    <div class="item">
      <%= image_tag ("slider4.png")%>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>