config/routes.rb
Rails.application.routes.draw do
  get 'galleries/index'

  #get 'shop/index'

  devise_for :users
  resources :budgets
  resources :products 
  resources :categories
  resources :galleries
  resources :shop do
  	member do
  		post "add"
      post "restar"
      post "suma"
      post "deletedetalle"
      get "pdf"
      
  	end
      collection do
        get  "showallbudget"
      end 

  end
  root 'shop#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  respond_to :html, :json
  def index
    @search = Product.includes(:galleries).search(params[:q])
    @products = @search.result.includes(:category)
  	 # @products = Product.all


  end

def deletedetalle
  detallep = BudgetDetail.where(id: params[:id]).first
  presupuesto = Budget.find(detallep.budget_id)
  detallep.destroy
  detalle = presupuesto.budget_details.where(budget_id: presupuesto.id).first
  if !detalle

    msj="No hay mas productos en el presupuesto"
    flash[:notice]=msj
    presupuesto.destroy
    cookies.delete :budget_id
    cookies[:total_cart]= 0
    cookies[:moneda_total] = 0
    redirect_to root_path
  else
    cookies[:total_cart] = presupuesto.budget_details(:product_id).count
    moneda_total
    redirect_to shop_path
  end

  
end
        def restar
            presupuesto = Budget.find(cookies[:budget_id])

            detallep = BudgetDetail.where(id: params[:id]).first
            cantidad = detallep.cant

            if cantidad > 1
               detallep.cant -=1
            else
              detallep.destroy
            end
            detallep.save if detallep
              detalle = presupuesto.budget_details.where(budget_id: presupuesto.id).first 
              if detalle
                cookies[:total_cart]= presupuesto.budget_details(:product_id).count
                moneda_total
                redirect_to shop_path
              else
                presupuesto.destroy
                cookies.delete :budget_id
                cookies[:total_cart]= 0 # cantidad en stock en el carrito
                cookies[:moneda_total] = 0 #cantidad en moneda total
                redirect_to root_path

            end
        end









  def suma
      detallep = BudgetDetail.where(id: params[:id]).first
      detallep.cant +=1
    
          detallep.save if detallep 
            moneda_total
            redirect_to shop_path
           
      
  end

   def add

             # cookies.delete :budget_id
          if cookies[:budget_id]
                b_id = cookies[:budget_id]
                @presupuesto = Budget.find(b_id)   
             else
                @presupuesto = Budget.new(fecha: Date.today)
          end


          producto = Product.find(params[:id])
          detalle = @presupuesto.budget_details.where(product_id: producto.id).first
          puts "***************** detalle *********************"
          puts detalle.inspect
          puts "*********"
          if detalle 
                puts "********** el detalle si existe *************"
                detalle.cant +=1
               
              else
                 @presupuesto.budget_details.build(cant: 1, product_id: producto.id)
              
           end

        #Person.select(:age).count
       detalle.save if detalle
        if @presupuesto.save
          cookies[:total_cart] =@presupuesto.budget_details(:product_id).count

            cookies[:budget_id] =  @presupuesto.id
            moneda_total
            mss="se agrego  #{producto.name} presupuesto"
            flash[:notification] = "Post successfully created"

        else
            mss=" no se agrego producto al presupuesto"
            flash[:error]=mss
        end
        
         redirect_to root_path
      
  end


def moneda_total
  @sumtotal = 0
  @presupuesto = Budget.includes(budget_details: :product).find(cookies[:budget_id])
     @presupuesto.budget_details.each do |detalle| 
       @sumtotal = @sumtotal + (detalle.cant * detalle.product.price) 
    end
    cookies[:moneda_total]=@sumtotal 
    puts "************* total *************"
    puts cookies[:moneda_total].inspect
end

  def show
    # @varinstancia varlocal
    @presupuesto = Budget.includes(budget_details: :product).find(cookies[:budget_id])

   # @presupuesto = Budget.includes(:budget_details).find(params[:budget_id])

  end
  def showallbudget
    @presupuesto = Budget.includes(budget_details: :product).all

  end

 def pdf
          @presupuesto = Budget.includes(budget_details: :product).find(cookies[:budget_id])
          respond_to do |format|
          format.html
          format.pdf do 
            render :pdf         => "Presupuesto",
            :template  => "shop/pdf",
            :layout => 'pdf.html',   
            :page_size => 'A4',
            :dpi=>'72',
             title: 'Presupuesto', 

            :margin => {:top => 20, :bottom =>10 }
          
      end
    end
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shop/_producto.html.erb
    


<div class="col-md-3 col-sm-2 col-sx-1   grid1_of_3"> 
  

    <%= link_to product do %>
    
				<% product.galleries.each do |p| %>
					<% if p.image_check ==true %>
						<%=image_tag(p.photo.url)  %>
					<%end%>
				<%end%>


            <% end %>
          <h3><%= product.name%></h3>
          <div class="price">
            <h4>$ <%= product.price%><span><%=  link_to 'Add to Cart', add_shop_path(product),class: "cart_add",remote: true, method: :post  %></span></h4>
          </div>
          <span class="b_btm"></span>
   
 

</div>



     

app/views/shop/index.html.erb
<div class="main_bg">
<div class="wrap">	
	<div class="main">

	







       




<div class="row">

  <% if flash[:success] %>

     <% end %> 

</div>



  <% if flash[:notification] %>
  <div class="alert alert-success "><%= flash[:notification] %></div>

  <% end %>
<div class="col-md-9">
        <% @products.each do |product| %>
        
                <%= render 'producto', product: product %>
          


        <% end %>
</div>
<div class="col-md-3">
<div class="panel panel-default">
  <div class="panel-body">


         <%= search_form_for @search, :url => { :action => :index } do |f| %>



            <div class="row">
            <div class="col-md-12">
                  <div class="form-group">
                  <%= f.label :name_cont, "Producto" %>
                  <%= f.search_field :name_cont, :class=>"form-control input-sm"%>
                  </div>
            </div>
            </div>
              

           

<div class="row">
<div class="col-md-12">
    <div class="form-group">
               <%= f.label :category_name_start, "Categoria" %>

          <%= f.search_field :category_name_start,:class=>"form-control input-sm" %>
  </div>
</div>

</div>


<div class="row">
<div class="col-md-12">
 <%= f.label :price_gteq, "Rango de Precios" %>
</div>
  <div class="col-md-6">
<div class="form-group">
  <%= f.search_field :price_gteq , :class=>"form-control input-sm"%>
</div>
  </div>

  <div class="col-md-6">

<div class="form-group">
   <%= f.search_field :price_lteq , :class=>"form-control input-sm"%> 
</div>
  </div>
</div>




          <div class="actions"><%= f.submit :value=>"Buscar", :class=>".btn btn-default btn-sm btn-block" %></div>

          </div>

         
        <% end %>
  </div>
</div>
</div>


					


		</div>
</div>
</div>
         <script>
    //   $(document).ready(function() {
    //        setTimeout(function() {
    //     $(".disappear").fadeOut(1500);
    // },2000);
    //        $('button').click(function(){
    //     $('.alert').show()
    // }) 

    //     });
    </script>

app/views/shop/pdf.pdf.erb
<% @total =0%>
<div class="container">
      
  <table class="table table-striped">
    <thead>
      <tr>
    
        <th>Producto</th>
        <th>cantidad</th>
        <th>Precio</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody id="detalleview">
    <% @presupuesto.budget_details.each do |detalle| %>
      <tr>

        <td><%= detalle.product.name	 %>	</td>
        <td><%= detalle.cant	 %>	</td>
        <td><%= number_to_currency(detalle.product.price) %></td>
        <td><%= number_to_currency(detalle.cant * detalle.product.price) %></td>

        
     
        <% @total = @total + (detalle.cant * detalle.product.price) %>
      </tr>
     
      <%end%>
      <tr>
		<td></td>
		<td></td>
		<td>Total</td>
		<td><%= number_to_currency(@total) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/shop/show.html.erb
<% @total =0%>
<div class="container">
      
       
          <%= link_to 'Imprimir <i class="fa fa-print" aria-hidden="true"></i>'.html_safe, pdf_shop_path(format: :pdf), :target => '_blank',class: 'btn btn-default'  %>  <span>
  <table class="table">
    <thead>
      <tr>
      <th></th>
        <th>Producto</th>
        <th>cantidad</th>
        <th>Precio</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody id="detalleview">


    <% @presupuesto.budget_details.each do |detalle| %>
      <tr>
      <td>

        <% detalle.product.galleries.each do |gallery|%>

            <%if gallery.image_check ==true %>
               <%=image_tag(gallery.photo.url) %>
            <%end%>
        <%end%>
     


      </td>
        <td><%= detalle.product.name	 %>	</td>

        <td><%= detalle.cant %> </td>

        <td><%= number_to_currency(detalle.product.price) %></td>
        <td><%= number_to_currency(detalle.cant * detalle.product.price) %></td>

        <td><%=  link_to '<i class="fa fa-minus" aria-hidden="true"></i>'.html_safe,  restar_shop_path(detalle),remote: true, class: 'btn btn-default btn-smtag-tooltip',:data => {:toggle=>"tooltip"},
                    'data-original-title' => "Restar", method: :post  %>  
         <%=  link_to '<i class="fa fa-plus" aria-hidden="true"></i>'.html_safe, suma_shop_path(detalle),remote: true,  class: 'btn btn-default btn-smtag-tooltip',:data => {:toggle=>"tooltip"},
                    'data-original-title' => "sumar", method: :post  %></td>

        <td><%=  link_to '<i class="fa fa-trash-o " aria-hidden="true"></i>'.html_safe, deletedetalle_shop_path(detalle), remote: true,class: 'btn btn-default btn-smtag-tooltip',:data => {:toggle=>"tooltip"},
                    'data-original-title' => "Eliminar detalle", method: :post  %></td>
        
     


        <% @total = @total + (detalle.cant * detalle.product.price) %>
      </tr>
     
      <%end%>
      <tr>
		<td></td>
		<td></td>
		<td>Total</td>
    <td></td>
		<td> <h4> <%= number_to_currency(@total) %></h4>  </td>
      </tr>


    </tbody>



    
  </table>
</div>

app/views/shop/showallbudget.html.erb
<% @total =0%>
<div class="container">
         
  <table class="table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>cantidad</th>
        <th>Precio</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody id="detalleview">
    <% @presupuesto.budget_details.each do |detalle| %>
      <tr>
        <td><%= detalle.product.name	 %>	</td>
        <td><%= detalle.cant	 %>	</td>
        <td><%= number_to_currency(detalle.product.price) %></td>
        <td><%= number_to_currency(detalle.cant * detalle.product.price) %></td>
        <td><%=  link_to 'restar', restar_shop_path(detalle),remote: true, class: 'btn btn-default btn-sm', method: :post  %></td>
        <td><%=  link_to 'suma', suma_shop_path(detalle),remote: true,  class: 'btn btn-default btn-sm', method: :post  %></td>
        <td><%=  link_to 'eliminar', deletedetalle_shop_path(detalle), remote: true,class: 'btn btn-default btn-sm', method: :post  %></td>
        <% @total = @total + (detalle.cant * detalle.product.price) %>
      </tr>
     
      <%end%>
      <tr>
		<td></td>
		<td></td>
		<td>Total</td>
    <td></td> 
   
		<td><%= number_to_currency(@total) %></td>
      </tr>
    </tbody>
  </table>
</div>