config/routes.rb
Rails.application.routes.draw do
  get 'galleries/index'

  #get 'shop/index'

  devise_for :users
  resources :budgets
  resources :products 
  resources :categories
  resources :galleries
  resources :shop do
  	member do
  		post "add"
      post "restar"
      post "suma"
      post "deletedetalle"
      get "pdf"
      
  	end
      collection do
        get  "showallbudget"
      end 

  end
  root 'shop#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	validates :name,  presence:  { message: "Campo obligatorio" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
   # load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  
    respond_modal_with @category_params
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    puts "la concha de la lora +++++++++++++++++++++++++++++++"
    @category = Category.new(category_params)
      
    @category.save
    respond_modal_with @category, location: @category
    # respond_to do |format|
    #   if @category.save
    #     format.html { redirect_to @category, notice: 'Category was successfully created.' }
    #     format.json { render :show, status: :created, location: @category }
    #   else

    #      format.html { render :new }
    #     format.json { render json: @category.errors, status: :unprocessable_entity }

    #   end
    # end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category,  remote: request.xhr?, html: { data: { modal: true } }) do |f| %>

<div class="row">
  <div class="col-md-12">
  <div class="form-group <%= @category.errors[:legajo].any? ? " has-error has-feedback" : "" %>">
 <div class="field">
    <%= f.label :name, "Categoria" %>
    <%= f.text_field :name , autofocus: true, :class=>"form-control " ,placeholder: "Categoria"%>
      <%if @category.errors[:name].any? %>
                                        <span class="glyphicon  form-control-feedback"><i class="fa fa-exclamation" aria-hidden="true"></i>
                                        </span>
                                        <p class="bg-warning"><%= @category.errors[:name].to_s[/\w([^"]*)/] %></p>
                                <% end %>
  </div>
  </div>
  </div>

</div>



















 

<div class="row">
  <div class="col-md-2 col-md-offset-8">
        
           <%= f.submit  :value=>"Guardar", :class=>".btn btn-info btn-lg"%>

  </div>
</div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
    <div class="row">
                            <%= link_to 'Volver al Listado <i class="fa fa-hand-o-left fa-1x" aria-hidden="true"></i>'.html_safe, categories_path,class: 'btn btn-default', title:"Volver"  %>  
                      
                                                      
         

  </div>

</div>
<br>
<div class="container">
	<div class="col-md-6">
<div class="panel panel-default">
  <div class="panel-heading">Edicion de Categoria</div>
  <div class="panel-body">
<%= render 'form', category: @category %>
  </div>
</div>
	</div>

</div>

app/views/categories/index.html.erb
<div class="container">

<div class="panel panel-default">
  <div class="panel-heading"><h3>Categorias </h3></div>
  <div class="panel-body">
   

<%= link_to 'Create category', new_category_path, 
            data: { modal: true } %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Categoria</th>

      </tr>
    </thead>
    <tbody>
        <% @categories.each do |category| %>

      <tr>
            <td><%= category.name %></td>
<td>

             <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, category,class: 'btn btn-default'  %>  <span>
        <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
'.html_safe,edit_category_path(category),class: 'btn btn-default'  %>  <span>
        <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>
'.html_safe, category, method: :delete, data: { confirm: 'Seguro que desea eliminar la categoria?' },class: 'btn btn-default'  %>  <span>



</td>
 






      

           

      </tr>
 <% end %>
    </tbody>
  </table>





  </div>
</div>
</div>

app/views/categories/new.html.erb
<div class="container">
    <div class="row">
                            <%= link_to 'Volver al Listado <i class="fa fa-hand-o-left fa-1x" aria-hidden="true"></i>'.html_safe, categories_path,class: 'btn btn-default', title:"Volver"  %>  
                      
                                                      
         

  </div>

</div>
<br>
<div class="container">
	<div class="col-md-6">
<div class="panel panel-default">
  <div class="panel-heading">Carga de Categoria</div>
  <div class="panel-body">
<%= render 'form', category: @category %>
  </div>
</div>
	</div>

</div>

app/views/categories/show.html.erb
<div class="container">
    <div class="row">
                            <%= link_to ' Listado Categoria <i class="fa fa-list  fa-1x" aria-hidden="true"></i>'.html_safe, categories_path,class: 'btn btn-default', title:"Volver"  %> 
                      
                           <%= link_to 'Editar Categoria <i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i>
'.html_safe, edit_category_path(@category),class: 'btn btn-default', title:"Editar"  %>                            
         

  </div>

</div>
<div class="container">
	
<div class="col-md-6">
<div class="panel panel-default">
  <div class="panel-heading"></div>
  <div class="panel-body">
    <p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
  </div>
</div>
</div>

</div>