config/routes.rb
Rails.application.routes.draw do
  get 'galleries/index'

  #get 'shop/index'

  devise_for :users
  resources :budgets
  resources :products 
  resources :categories
  resources :galleries
  resources :shop do
  	member do
  		post "add"
      post "restar"
      post "suma"
      post "deletedetalle"
      get "pdf"
      
  	end
      collection do
        get  "showallbudget"
      end 

  end
  root 'shop#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
require 'carrierwave/orm/activerecord'
class Product < ApplicationRecord
	belongs_to :category
	 validates_associated :category
	has_many :budget_details
	 has_many :galleries
	 accepts_nested_attributes_for :galleries,  allow_destroy: true
	
	validates :name,  presence: { message: "Campo obligatorio" }
	validates :description,  presence: { message: "Campo obligatorio" }
	#validates :quantity, numericality: { only_integer: true }
	validates :quantity, presence: false
	#validates :quantity, numericality:{only_integer: true, greater_than: 0, :message => "El valor ingresado tiene que ser mayor a cero"}
	validates :price, presence: { message: "Campo obligatorio" }
	validates :price, numericality:{only_integer:false,  greater_than: 0, :message => "No se permite un precio vacio o negativo"}
	mount_uploader :photo, ImageUploader 

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]
respond_to :html, :json
  # GET /products
  # GET /products.json
  def index
    # @products = Product.all

     @products = Product.includes(:galleries).all
   # @categories = set_category;

  end

  # GET /products/1
  # GET /products/1.json
  def show
    # @product.galleries
   # @product = Product.includes(:galleries).find(params[:id]);
   # @galleries = @product.galleries.all
   #@categories = set_category;
   puts"*********************************"
  end

  # GET /products/new
  def new
    @product = Product.new  
    @product.galleries.build
    @categories = Category.all
    respond_modal_with @product
    # @galleries = @product.galleries.build
  end

  # GET /products/1/edit
  def edit
    @product.galleries
    # @product = Product.find(params[:id]);
    # @galleries = @product.galleries.all
       # @product = Product.includes(:galleries).find(params[:id]);

    @categories = Category.select("id,name").where(:id => params[:id]);

  end

  # POST /products
  # POST /products.json
  def create

     @product = Product.new(product_params)
     @product.save
     respond_modal_with @product, location: @product
 
    # respond_to do |format|
    #   if @product.save

    #     format.html { redirect_to @product, notice: 'Product was successfully created.' }
    #     format.json { render :show, status: :created, location: @product }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @product.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :photo, :quantity, :price, :description, :category_id, :name, galleries_attributes: [:id, :photo, :image_check, :_destroy])
    end
     def category_params
      params.require(:product).permit(:name, :photo, :quantity, :price, :description)
    end
    def set_category
     @categories= Category.select("id, name").where(:id => params[:id]);
    end
end
# , galleries_attributes: [:id, :product_id, :photo, :photo_cache]

app/helpers/products_helper.rb
module ProductsHelper
def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |gallery|
      render(association.to_s.singularize + "_fields", f: gallery)
    end
    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
  end
end
	

app/views/products/_form.html.erb
<%= form_for(product,remote: request.xhr?, html: { data: { modal: true } }) do |f| %>



<div class="container">
    <div class="row">
    <div class="col-md-10 col-md-offet-2">
          <div class="form-group <%= @product.errors[:name].any? ? " has-error has-feedback" : "" %>">
              <%= f.label :name, "Nombre"  %>
              <%= f.text_field :name , autofocus: true, :class=>"form-control " ,placeholder: "Nombre"%>
                    <%if @product.errors[:name].any? %>
                                        <span class="glyphicon  form-control-feedback"><i class="fa fa-exclamation" aria-hidden="true"></i>
                                        </span>
                                        <p class="bg-warning"><%= @product.errors[:name].to_s[/\w([^"]*)/] %></p>
                                <% end %>
          </div>






          <div class="form-group  <%= @product.errors[:description].any? ? " has-error has-feedback" : "" %>">
              <%= f.label :description, "Descripcion"  %>
              <%= f.text_area :description , autofocus: true, :class=>"form-control ", :rows=>"2" ,placeholder: "Descripcion"%>
                <%if @product.errors[:description].any? %>
                                        <span class="glyphicon  form-control-feedback"><i class="fa fa-exclamation" aria-hidden="true"></i>
                                        </span>
                                        <p class="bg-warning"><%= @product.errors[:description].to_s[/\w([^"]*)/] %></p>
                                <% end %>
          </div>


          <div class="row">
             <div class="col-md-4">
                 <div class="form-group <%= @product.errors[:price].any? ? " has-error has-feedback" : "" %>">
              <%= f.label :price, "Precio"  %>
              <%= f.text_field :price , autofocus: true, :class=>"form-control " ,placeholder: "Precio"%>
                <%if @product.errors[:price].any? %>
                                        <span class="glyphicon  form-control-feedback"><i class="fa fa-exclamation" aria-hidden="true"></i>
                                        </span>
                                        <p class="bg-warning"><%= @product.errors[:price].to_s[/\w([^"]*)/] %></p>
                                <% end %>
          </div>




             </div>
             <div class="col-md-4">
               <div class="form-group">
              <%= f.label :category, "Categoria"  %>
              <br>
              <%=
              f.collection_select( :category_id, Category.all, :id, :name, prompt: "Seleccione una categoria",class: "form-control input-md")
              %>
          </div>

             </div>
          </div>
         
        
         <div class="col">
           <div class="col-md-6">
             <div class="form-group ">
                      <%= f.fields_for :galleries do |gallery| %>
                          <%= render 'gallery_fields', f: gallery %>
                      <%end%>  
                      <%= link_to_add_fields 'Agregar Imagen <i class="fa fa-plus fa-1x" aria-hidden="true"></i>'.html_safe, f, :galleries %>
             
           </div>
          
         </div>

    </div>

      


<div class="row">
  <div class="col-md-2 col-md-offset-8">
        
           <%= f.submit  :value=>"Guardar", :class=>".btn btn-info btn-lg"%>

  </div>
</div>



</div>



<% end %>

app/views/products/_gallery_fields.html.erb
<fieldset>
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">
				<div class="col-md-10">
					<div class="form-group ">
						<%= f.label :photo, "Imagen" %>
						<%= f.file_field :photo, class: "btn btn-info btn-xs"%>
						<%= f.hidden_field :photo_cache %>
				
					</div>

	
				</div>
				<div class="col-md-2">
					 <%= f.check_box :image_check %>
				</div>

			</div>
			          <%= f.hidden_field :_destroy %>
  <%= link_to  'Eliminar Imagen <i class="fa fa-times fa-1x" aria-hidden="true"></i>'.html_safe, '#', class: "remove_fields btn btn-danger" %>
		</div>
		
	</div>
</fieldset>

app/views/products/copyshow.html.erb
<!-- start main -->
<div class="main_bg">
<div class="wrap">  
  <div class="main">
  <!-- start content -->













  <div class="single">
      <!-- start span1_of_1 -->
      <div class="left_content"><!-- el contennido del producto -->



      <div class="span1_of_1"><!-- las imagenes del product con las preview de las otras imagenes -->
        <!-- start product_slider -->
        <div class="product-view">
            <div class="product-essential">
                <div class="product-img-box">

<!-- 
mini views
-->
<div class="col-md-3">
      <div class="more-views" style="float:left;">
                <div class="more-views-container">
                <ul>
                <% @product.galleries.each do |p| %>
                    <li>
                    <%=image_tag(p.photo.url, width: "64", height: "85")  %>
                              
                    </li>
                    <%end%>
                  </ul>
                </div>
            </div>
</div>
<div class="col-md-9">
  <% @product.galleries.each do |p| %>


    <% if p.image_check ==true %>
            <div class="product-image"> 
           
                   
                    <%=image_tag(p.photo.url)  %>

             
           </div>

<%end%>
<% end %>
</div>




            


        
        </div>
        </div>
        </div>
        <!-- end product_slider -->
      </div>
      <!-- start span1_of_1 -->




      <div class="span1_of_1_des">
          <div class="desc1">
          <h3> <%= @product.name %> </h3>
          <p> <%= @product.description %>.</p>
          <h5>$.  <%= @product.price %> </h5>
          <div class="available">
            
          
              <div class="price">
            <h4><span><%=  link_to 'Add to Cart', add_shop_path(@product),class: "cart_add",remote: true, method: :post  %></span></h4>
          </div>
          
            <div class="clear"></div>
          </div>
      
           </div>
          </div>
          <div class="clear"></div>
         
          </div>
          <!-- start sidebar -->
    
                <div class="clear"></div>
         </div> 
  <!-- end content -->








 <div class="left_sidebar">
          <div class="sellers">
            <h4>Acciones</h4>
              <div class="single-nav">
                      <ul>
                        <%= link_to 'Volver al Listado <i class="fa fa-hand-o-left fa-1x" aria-hidden="true"></i>'.html_safe, root_path,class: 'btn btn-default', title:"Volver"  %>  
                        <br/><br/>
                           <%= link_to 'Editar Producto <i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i>
'.html_safe, edit_product_path(@product),class: 'btn btn-default', title:"Editar"  %>                            
                      </ul>
                    </div>
            </div>
            </div>






  </div>
</div>
</div>    

<!-- *******************************************************************************-->

app/views/products/edit.html.erb
<div class="container">
    <div class="row">
                            <%= link_to 'Volver al Listado <i class="fa fa-hand-o-left fa-1x" aria-hidden="true"></i>'.html_safe, products_path,class: 'btn btn-default', title:"Volver"  %>  
                      
                                                      
         

  </div>

</div>
<br>
<div class="container">
<div class="panel panel-default">
  <div class="panel-heading">Editar producto</div>
  <div class="panel-body">
<%= render 'form', product: @product %>
  </div>
</div>	

</div>

app/views/products/index.html.erb
<div class="container">
          <%= link_to 'Create product', new_product_path, 
            data: { modal: true } %> 
  <table class="table table-hover  productTable">
    <thead>
      <tr>
      <th></th>
        <th>Producto</th>
        <th class="coldescription">Descripcion</th>
        <th>Precio</th>
        
       <th>Acciones</th>
        
      </tr>
    </thead>
    <tbody >
     <% @products.each do |product| %>
      <tr>
      <td>

    <% product.galleries.each do |p| %>
      <% if p.image_check ==true %>
       <%=image_tag(p.photo.url)  %>
       <%end%>
    <%end%>
       
        
        
         </td>
        <td><%= product.name %></td>
        <td class="coldescription"><%= product.description%></td>
        <td><%= product.price %></td>
        <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, product,class: 'btn btn-default'  %>  <span>
        <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
'.html_safe, edit_product_path(product),class: 'btn btn-default'  %>  <span>
        <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>
'.html_safe, product, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-default'  %>  <span></td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="container">
    <div class="row">
                            <%= link_to 'Volver al Listado <i class="fa fa-hand-o-left fa-1x" aria-hidden="true"></i>'.html_safe, products_path,class: 'btn btn-default', title:"Volver"  %>  
                      
                                                      
         

  </div>

</div>
<br>
<div class="container">
	
<div class="panel panel-default">
  <div class="panel-heading">Carga de Producto</div>
  <div class="panel-body">
<%= render 'form', product: @product %>
  </div>
</div>
</div>

app/views/products/show.html.erb
<div class="container">
    <div class="row">
    <% if user_signed_in? %>
                            <%= link_to 'Volver al Listado <i class="fa fa-hand-o-left fa-1x" aria-hidden="true"></i>'.html_safe, products_path,class: 'btn btn-default', title:"Volver"  %> 
                      
                           <%= link_to 'Editar Producto <i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i>
'.html_safe, edit_product_path(@product),class: 'btn btn-default', title:"Editar"  %>                            
         
<%end%>
  </div>

</div>
<br/>


                    
        
                  
           
<div class="container">
  
        <div id="main_area">
                <!-- Slider -->
                <div class="row">
                    <div class="col-xs-12" id="slider">
                        <!-- Top part of the slider -->
                        <div class="row">
                            <div class="col-sm-8" id="carousel-bounding-box">
                                <div class="carousel slide" id="myCarousel">
                                    <!-- Carousel items -->
                                    <div class="carousel-inner">


  <!-- contenido que se muestra en el slaider-->

      <% @product.galleries.each do |p| %>
         <% if p.image_check ==true %>
                  <div class="active item" data-slide-number="<%=p.id%>">
                  <%=image_tag(p.photo.url, width: "64", height: "85") %>
             
                  </div>
              <%else%>
                 <div class="item" data-slide-number="<%=p.id%>">
                  <%=image_tag(p.photo.url, width: "64", height: "85") %>
             
                  </div>
              <%end%>
     <%end%>

  <!-- end contenido que se muestra en el slaider-->



                                    </div><!-- Carousel nav -->

                                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left"></span>                                       
                                    </a>
                                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right"></span>                                       
                                    </a>                                
                                    </div>
                            </div>

                            <div class="col-sm-4" id="carousel-text">


                            </div>

                            <div id="slide-content" ">

                            <!-- bloque que repite-->
                          
                                          <div class="desc1">
                              <h3> <%= @product.name %> </h3>
                              <p> <%= @product.description %>.</p>
                              <h5>$.  <%= @product.price %> </h5>
                              <div class="available">


                              <div class="price">
                              <h4><span><%=  link_to 'Add to Cart', add_shop_path(@product),class: "cart_add",remote: true, method: :post  %></span></h4>
                              </div>

                              <div class="clear"></div>
                              </div>

                              </div>
                            <!-- bloque que repite-->
                        
                            </div>
                        </div>
                    </div>
                </div><!--/Slider-->
                
                <div class="row hidden-xs" id="slider-thumbs">
                        <!-- Bottom switcher of slider -->
                        <ul class="hide-bullets">
                          <% @product.galleries.each do |p| %>
                            <li class="col-xs-2">
                                <a class="thumbnail" id="carousel-selector-<%=p.id%>"><%=image_tag(p.photo.url) %></a>
                            </li>
                            <%end%>

                           

                           

                        </ul>                 
                </div>

</div>











































</d iv>
    